collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

domain: new.weronikapenar.pl
url: https://new.weronikapenar.pl
baseurl: ""
timezone: Europe/Warsaw

exclude:
  - .bundle
