collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: authors
    values:
      layout: author
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

domain: michcio1234.github.io
url: https://michcio1234.github.io
baseurl: /weronikapenar/
timezone: Europe/Warsaw

exclude:
  - .bundle
